// Angular Imports
import { type ComponentFixture, TestBed } from '@angular/core/testing'
import { Component } from '@angular/core'
// This Component Imports
import { ImageComponent } from './image.component'

@Component({
	template: `<app-image priority [src]="src" [alt]="alt" />`,
	standalone: true,
	imports: [ImageComponent],
})
class HostComponent {
	src = 'https://assets.iamgld.dev/images/iamgld-face.webp'
	alt = 'iamgld face generated by https://notion.com/faces'
}

describe('ImageComponent via HostComponent', () => {
	let hostFixture: ComponentFixture<HostComponent>

	beforeEach(async () => {
		// Agrega el preconnect al head para evitar el warning de NgOptimizedImage
		if (!document.head.querySelector('link[rel="preconnect"][href="https://assets.iamgld.dev"]')) {
			const link = document.createElement('link')
			link.rel = 'preconnect'
			link.href = 'https://assets.iamgld.dev'
			document.head.appendChild(link)
		}
		await TestBed.configureTestingModule({
			imports: [ImageComponent, HostComponent],
		}).compileComponents()

		hostFixture = TestBed.createComponent(HostComponent)
		hostFixture.detectChanges()
	})

	test('should render image', () => {
		const img = hostFixture.nativeElement.querySelector('img')
		expect(img).toBeTruthy()
		expect(img.src).toContain('iamgld-face.webp')
		expect(img.alt).toContain('iamgld face')
	})
})
