export const heroes = [
	{
		id: 1,
		name: 'A-Bomb',
		slug: '1-a-bomb',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/1-a-bomb.jpg',
		work: 'Musician, adventurer, author; formerly talk show host',
		biography: {
			fullName: 'Richard Milhouse Jones',
			alterEgos: 'No alter egos found.',
			aliases: ['Rick Jones'],
			firstAppearance: 'Hulk Vol 2 #2 (April, 2008) (as A-Bomb)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 2,
		name: 'Abe Sapien',
		slug: '2-abe-sapien',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/2-abe-sapien.jpg',
		work: 'Paranormal Investigator',
		biography: {
			fullName: 'Abraham Sapien',
			alterEgos: 'No alter egos found.',
			aliases: ['Langdon Everett Caul', 'Abraham Sapien', 'Langdon Caul'],
			firstAppearance: 'Hellboy: Seed of Destruction (1993)',
			publisher: 'Dark Horse Comics',
		},
	},
	{
		id: 3,
		name: 'Abin Sur',
		slug: '3-abin-sur',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/3-abin-sur.jpg',
		work: 'Green Lantern, former history professor',
		biography: {
			fullName: '',
			alterEgos: 'No alter egos found.',
			aliases: ['Lagzia'],
			firstAppearance: 'Showcase #22 (October, 1959)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 4,
		name: 'Adam Monroe',
		slug: '4-adam-monroe',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/4-adam-monroe.jpg',
		work: 'Adventurer, former samurai, soldier',
		biography: {
			fullName: 'Takezo Kensei',
			alterEgos: 'No alter egos found.',
			aliases: ['Kensei', 'Richard Sanders'],
			firstAppearance: 'Heroes S02E01 (2007)',
			publisher: 'NBC - Heroes',
		},
	},
	{
		id: 5,
		name: 'Adam Strange',
		slug: '5-adam-strange',
		gender: 'male',
		image:
			'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/5-adam-strange.jpg',
		work: 'Archaeologist, adventurer',
		biography: {
			fullName: 'Adam Strange',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'Showcase #17 (1958)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 6,
		name: 'Agent 13',
		slug: '6-agent-13',
		gender: 'female',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/6-agent-13.jpg',
		work: 'S.H.I.E.L.D. agent',
		biography: {
			fullName: 'Sharon Carter',
			alterEgos: 'No alter egos found.',
			aliases: ['Agent 13'],
			firstAppearance: 'Tales of Suspense #75 (1966)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 7,
		name: 'Agent Bob',
		slug: '7-agent-bob',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/7-agent-bob.jpg',
		work: 'Hydra agent',
		biography: {
			fullName: 'Bob',
			alterEgos: 'No alter egos found.',
			aliases: ['Agent of Hydra'],
			firstAppearance: 'Cable & Deadpool #38 (2007)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 8,
		name: 'Air-Walker',
		slug: '8-air-walker',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/8-air-walker.jpg',
		work: 'Former Xandarian Nova Corps officer',
		biography: {
			fullName: 'Gabriel Lan',
			alterEgos: 'No alter egos found.',
			aliases: ['Gabriel Lan'],
			firstAppearance: 'Fantastic Four #120 (1972)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 9,
		name: 'Ajax',
		slug: '9-ajax',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/9-ajax.jpg',
		work: 'Enforcer',
		biography: {
			fullName: 'Francis',
			alterEgos: 'No alter egos found.',
			aliases: ['Francis'],
			firstAppearance: 'Deadpool #14 (1998)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 10,
		name: 'Alan Scott',
		slug: '10-alan-scott',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/10-alan-scott.jpg',
		work: 'Engineer',
		biography: {
			fullName: 'Alan Ladd Wellington Scott',
			alterEgos: 'No alter egos found.',
			aliases: ['Green Lantern'],
			firstAppearance: 'All-American Comics #16 (1940)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 11,
		name: 'Alex Mercer',
		slug: '11-alex-mercer',
		gender: 'male',
		image:
			'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/11-alex-mercer.jpg',
		work: 'Scientist',
		biography: {
			fullName: 'Alexander J. Mercer',
			alterEgos: 'No alter egos found.',
			aliases: ['Prototype'],
			firstAppearance: 'Prototype (2009)',
			publisher: 'Activision',
		},
	},
	{
		id: 12,
		name: 'Alex Woolsly',
		slug: '12-alex-woolsly',
		gender: 'male',
		image:
			'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/12-alex-woolsly.jpg',
		work: 'Scientist',
		biography: {
			fullName: 'Alex Woolsly',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'Stargate Atlantis (2004)',
			publisher: 'MGM',
		},
	},
	{
		id: 13,
		name: 'Alfred Pennyworth',
		slug: '13-alfred',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/13-alfred.jpg',
		work: 'Butler',
		biography: {
			fullName: 'Alfred Thaddeus Crane Pennyworth',
			alterEgos: 'No alter egos found.',
			aliases: ['Penny-One'],
			firstAppearance: 'Batman #16 (1943)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 14,
		name: 'Alien',
		slug: '14-alien',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/14-alien.jpg',
		work: 'Xenomorph',
		biography: {
			fullName: 'Unknown',
			alterEgos: 'No alter egos found.',
			aliases: ['Xenomorph'],
			firstAppearance: 'Alien (1979)',
			publisher: '20th Century Fox',
		},
	},
	{
		id: 15,
		name: 'Allan Quatermain',
		slug: '15-allan-quatermain',
		gender: 'male',
		image:
			'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/15-allan-quatermain.jpg',
		work: 'Adventurer',
		biography: {
			fullName: 'Allan Quatermain',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'King Solomon’s Mines (1885)',
			publisher: 'Alan Moore',
		},
	},
	{
		id: 16,
		name: 'Amazo',
		slug: '16-amazo',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/16-amazo.jpg',
		work: 'Android',
		biography: {
			fullName: 'Amazo',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'The Brave and the Bold #30 (1960)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 17,
		name: 'Ammo',
		slug: '17-ammo',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/17-ammo.jpg',
		work: 'Mercenary',
		biography: {
			fullName: 'Unknown',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'Punisher War Journal #1 (1988)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 18,
		name: 'Ando Masahashi',
		slug: '18-ando-masahashi',
		gender: 'male',
		image:
			'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/18-ando-masahashi.jpg',
		work: 'Office worker',
		biography: {
			fullName: 'Ando Masahashi',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'Heroes S01E01 (2006)',
			publisher: 'NBC - Heroes',
		},
	},
	{
		id: 19,
		name: 'Angel',
		slug: '19-angel',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/19-angel.jpg',
		work: 'Adventurer',
		biography: {
			fullName: 'Warren Kenneth Worthington III',
			alterEgos: 'Archangel',
			aliases: ['Angel', 'Archangel'],
			firstAppearance: 'X-Men #1 (1963)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 20,
		name: 'Angel Dust',
		slug: '20-angel-dust',
		gender: 'female',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/20-angel-dust.jpg',
		work: 'Mercenary',
		biography: {
			fullName: 'Christina',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'Morlocks #1 (2002)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 21,
		name: 'Angel Salvadore',
		slug: '21-angel-salvadore',
		gender: 'female',
		image:
			'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/21-angel-salvadore.jpg',
		work: 'Student',
		biography: {
			fullName: 'Angel Salvadore',
			alterEgos: 'No alter egos found.',
			aliases: ['Tempest'],
			firstAppearance: 'New X-Men #118 (2001)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 22,
		name: 'Animal Man',
		slug: '22-animal-man',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/22-animal-man.jpg',
		work: 'Adventurer',
		biography: {
			fullName: 'Bernhard Baker',
			alterEgos: 'No alter egos found.',
			aliases: ['Buddy Baker'],
			firstAppearance: 'Strange Adventures #180 (1965)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 23,
		name: 'Annihilus',
		slug: '23-annihilus',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/23-annihilus.jpg',
		work: 'Conqueror',
		biography: {
			fullName: 'Annihilus',
			alterEgos: 'No alter egos found.',
			aliases: ['The Living Death That Walks'],
			firstAppearance: 'Fantastic Four Annual #6 (1968)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 24,
		name: 'Ant-Man',
		slug: '24-ant-man',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/24-ant-man.jpg',
		work: 'Scientist, adventurer',
		biography: {
			fullName: 'Henry Jonathan Pym',
			alterEgos: 'Giant-Man, Goliath, Yellowjacket, Wasp',
			aliases: ['Hank Pym'],
			firstAppearance: 'Tales to Astonish #27 (1962)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 25,
		name: 'Anti-Monitor',
		slug: '25-anti-monitor',
		gender: 'male',
		image:
			'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/25-anti-monitor.jpg',
		work: 'Destroyer',
		biography: {
			fullName: 'Anti-Monitor',
			alterEgos: 'No alter egos found.',
			aliases: ['Monitor'],
			firstAppearance: 'Crisis on Infinite Earths #2 (1985)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 26,
		name: 'Anti-Spawn',
		slug: '26-anti-spawn',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/26-anti-spawn.jpg',
		work: 'Vigilante',
		biography: {
			fullName: 'Jason Wynn',
			alterEgos: 'No alter egos found.',
			aliases: ['Redeemer'],
			firstAppearance: 'Spawn #28 (1994)',
			publisher: 'Image Comics',
		},
	},
	{
		id: 27,
		name: 'Anti-Venom',
		slug: '27-anti-venom',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/27-anti-venom.jpg',
		work: 'Vigilante',
		biography: {
			fullName: 'Edward Charles Allan Brock',
			alterEgos: 'Venom, Toxin',
			aliases: ['Eddie Brock'],
			firstAppearance: 'The Amazing Spider-Man #569 (2008)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 28,
		name: 'Apocalypse',
		slug: '28-apocalypse',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/28-apocalypse.jpg',
		work: 'Conqueror',
		biography: {
			fullName: 'En Sabah Nur',
			alterEgos: 'No alter egos found.',
			aliases: ['The First One'],
			firstAppearance: 'X-Factor #5 (1986)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 29,
		name: 'Aquababy',
		slug: '29-aquababy',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/29-aquababy.jpg',
		work: 'Prince of Atlantis',
		biography: {
			fullName: 'Arthur Curry, Jr.',
			alterEgos: 'No alter egos found.',
			aliases: ['Aquababy'],
			firstAppearance: 'Aquaman #23 (1965)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 30,
		name: 'Aqualad',
		slug: '30-aqualad',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/30-aqualad.jpg',
		work: 'Adventurer',
		biography: {
			fullName: 'Garth',
			alterEgos: 'Tempest',
			aliases: ['Tempest'],
			firstAppearance: 'Adventure Comics #269 (1960)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 31,
		name: 'Aquaman',
		slug: '31-aquaman',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/31-aquaman.jpg',
		work: 'King of Atlantis',
		biography: {
			fullName: 'Arthur Curry',
			alterEgos: 'No alter egos found.',
			aliases: ['Orin'],
			firstAppearance: 'More Fun Comics #73 (1941)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 32,
		name: 'Arachne',
		slug: '32-arachne',
		gender: 'female',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/32-arachne.jpg',
		work: 'Adventurer',
		biography: {
			fullName: 'Julia Carpenter',
			alterEgos: 'Spider-Woman',
			aliases: ['Spider-Woman'],
			firstAppearance: 'Secret Wars #6 (1984)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 33,
		name: 'Archangel',
		slug: '33-archangel',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/33-archangel.jpg',
		work: 'Adventurer',
		biography: {
			fullName: 'Warren Kenneth Worthington III',
			alterEgos: 'Angel',
			aliases: ['Angel', 'Death'],
			firstAppearance: 'X-Factor #24 (1988)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 34,
		name: 'Arclight',
		slug: '34-arclight',
		gender: 'female',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/34-arclight.jpg',
		work: 'Mercenary',
		biography: {
			fullName: 'Philippa Sontag',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'X-Factor #10 (1986)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 35,
		name: 'Ardina',
		slug: '35-ardina',
		gender: 'female',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/35-ardina.jpg',
		work: 'Adventurer',
		biography: {
			fullName: 'Ardina',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'The Order #4 (2002)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 36,
		name: 'Ares',
		slug: '36-ares',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/36-ares.jpg',
		work: 'God of War',
		biography: {
			fullName: 'Ares',
			alterEgos: 'No alter egos found.',
			aliases: ['Mars'],
			firstAppearance: 'Thor #129 (1966)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 37,
		name: 'Arnim Zola',
		slug: '37-arnim-zola',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/37-arnim-zola.jpg',
		work: 'Biochemist',
		biography: {
			fullName: 'Arnim Zola',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'Captain America and the Falcon #208 (1977)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 38,
		name: 'Arrow',
		slug: '38-arrow',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/38-arrow.jpg',
		work: 'Vigilante',
		biography: {
			fullName: 'Oliver Queen',
			alterEgos: 'Green Arrow',
			aliases: ['Green Arrow'],
			firstAppearance: 'More Fun Comics #73 (1941)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 39,
		name: 'Arsenal',
		slug: '39-arsenal',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/39-arsenal.jpg',
		work: 'Vigilante',
		biography: {
			fullName: 'Roy Harper',
			alterEgos: 'Speedy',
			aliases: ['Speedy', 'Red Arrow'],
			firstAppearance: 'More Fun Comics #73 (1941)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 40,
		name: 'Astro Boy',
		slug: '40-astro-boy',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/40-astro-boy.jpg',
		work: 'Robot',
		biography: {
			fullName: 'Atom',
			alterEgos: 'No alter egos found.',
			aliases: ['Tetsuwan Atom'],
			firstAppearance: 'Astro Boy (1952)',
			publisher: 'Tezuka Productions',
		},
	},
	{
		id: 41,
		name: 'Atlas',
		slug: '41-atlas',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/41-atlas.jpg',
		work: 'Adventurer',
		biography: {
			fullName: 'Steve Rand',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'Tales to Astonish #70 (1965)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 42,
		name: 'Atom',
		slug: '42-atom',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/42-atom.jpg',
		work: 'Physicist',
		biography: {
			fullName: 'Ray Palmer',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'Showcase #34 (1961)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 43,
		name: 'Aurora',
		slug: '43-aurora',
		gender: 'female',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/43-aurora.jpg',
		work: 'Adventurer',
		biography: {
			fullName: 'Jeanne-Marie Beaubier',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'X-Men #120 (1979)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 44,
		name: 'Azazel',
		slug: '44-azazel',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/44-azazel.jpg',
		work: 'Demon',
		biography: {
			fullName: 'Azazel',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'Uncanny X-Men #428 (2003)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 45,
		name: 'Azrael',
		slug: '45-azrael',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/45-azrael.jpg',
		work: 'Vigilante',
		biography: {
			fullName: 'Jean-Paul Valley',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'Batman: Sword of Azrael #1 (1992)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 46,
		name: 'Bane',
		slug: '46-bane',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/46-bane.jpg',
		work: 'Mercenary',
		biography: {
			fullName: 'Unknown',
			alterEgos: 'No alter egos found.',
			aliases: ['None'],
			firstAppearance: 'Batman: Vengeance of Bane #1 (1993)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 47,
		name: 'Batgirl',
		slug: '47-batgirl',
		gender: 'female',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/47-batgirl.jpg',
		work: 'Vigilante',
		biography: {
			fullName: 'Barbara Gordon',
			alterEgos: 'Oracle',
			aliases: ['Oracle'],
			firstAppearance: 'Detective Comics #359 (1967)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 48,
		name: 'Batman',
		slug: '48-batman',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/48-batman.jpg',
		work: 'Vigilante, CEO',
		biography: {
			fullName: 'Bruce Wayne',
			alterEgos: 'No alter egos found.',
			aliases: ['The Dark Knight', 'Matches Malone'],
			firstAppearance: 'Detective Comics #27 (1939)',
			publisher: 'DC Comics',
		},
	},
	{
		id: 49,
		name: 'Beast',
		slug: '49-beast',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/49-beast.jpg',
		work: 'Scientist, adventurer',
		biography: {
			fullName: 'Henry Philip McCoy',
			alterEgos: 'No alter egos found.',
			aliases: ['Hank McCoy'],
			firstAppearance: 'X-Men #1 (1963)',
			publisher: 'Marvel Comics',
		},
	},
	{
		id: 50,
		name: 'Beetle',
		slug: '50-beetle',
		gender: 'male',
		image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/50-beetle.jpg',
		work: 'Criminal',
		biography: {
			fullName: 'Abner Jenkins',
			alterEgos: 'No alter egos found.',
			aliases: ['MACH-1', 'MACH-2', 'MACH-3', 'MACH-4', 'MACH-V'],
			firstAppearance: 'Strange Tales #123 (1964)',
			publisher: 'Marvel Comics',
		},
	},
]
