// Angular Imports
import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core'
import { RouterLink, RouterOutlet } from '@angular/router'
import { takeUntilDestroyed } from '@angular/core/rxjs-interop'
import { environment } from '@environment'
// Shared Imports
import { MaterialModule } from '@shared/modules'
import { ImageComponent, LoaderComponent } from '@shared/components'
import { LoaderService } from '@shared/services'

const components = [LoaderComponent, ImageComponent]

@Component({
	standalone: true,
	selector: 'app-root',
	imports: [RouterOutlet, RouterLink, MaterialModule, ...components],
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.scss'],
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
	readonly #loaderService = inject(LoaderService)
	readonly #destroyRef = inject(DestroyRef)

	loading = signal(false)

	iamgldFaceImage = signal<IamgldFaceImage>({
		src: `${environment.cloudflareIamgldAssetsBucket}/images/iamgld-face.webp`,
		alt: 'iamgld face generated by https://notion.com/faces',
	})

	constructor() {
		this.#loaderService
			.isLoading()
			.pipe(takeUntilDestroyed(this.#destroyRef))
			.subscribe({
				next: (isLoading) => {
					this.loading.set(isLoading)
				},
				error: (error) => {
					console.error('Error fetching loader:', error)
					this.loading.set(false)
				},
			})
	}

	navigateToIamgld() {
		window.open('https://iamgld.dev', '_blank')
	}
}

interface IamgldFaceImage {
	src: string
	alt: string
}
